version: "3"
services:
    db:
        #volumes:
            #Uncomment for persistance\
            #- my-datavolume:/var/lib/mysql

        ports:
            - "3310:3306"

        #volumes:
        #      - my-datavolume:/var/lib/mysql
        image: mysql
        environment:
            MYSQL_DATABASE: aopblog
            #In the real world it's good idea to store the password and the username in file on the host and bind them with postfix _FILE
            MYSQL_ROOT_PASSWORD: aopblog
            MYSQL_PASSWORD: aopblog
            MYSQL_USER: aopblog
        networks:
            net:
                aliases:
                    - db
    php:
        image: aop-blog
        depends_on:
            - db
        volumes:
            - .:/code
        command: ["/code/bin/wait_for_mysql.sh", "db", "cd /code/ && ./bin/docker_afterdeploy.sh prod && php-fpm"]
        tty: true
        networks:
            net:
                aliases:
                     - php
    web:
        image: nginx:latest
        ports:
            - "8097:80"
        depends_on:
            - db
            - php
        volumes:
            - .:/code
            - ./app/config/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            net:
                aliases:
                    - web

    smtp:
        image: mwader/postfix-relay
        environment:
           - POSTFIX_myhostname=aop-blog.com
        networks:
            net:
                aliases:
                    - smtp

networks:
    net:

