version: "3"
services:
    db:
        volumes:
            - .:/code
        ports:
            - "3310:3306"
        image: mysql
        environment:
                MYSQL_USER: root
                MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            net:
                aliases:
                    - db
    php:
        image: aop-blog
        depends_on:
            - db
        volumes:
            - .:/code
        command: ["/code/bin/wait_for_mysql.sh", "db", "cd /code/ && ./bin/docker_afterdeploy.sh prod && php-fpm"]
        tty: true
        networks:
            net:
                aliases:
                     - php
    web:
        image: nginx:latest
        ports:
            - "127.0.0.1:8097:80"
        depends_on:
            - db
            - php
        volumes:
            - .:/code
            - ./app/config/nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            net:
                aliases:
                    - web

    smtp:
        image: mwader/postfix-relay
        environment:
           - POSTFIX_myhostname=aop-blog.ru
        networks:
            net:
                aliases:
                    - smtp

networks:
    net:

